<?php
/**
 * Standalone tests for drop-in version staleness detection (GH #27).
 *
 * wp-content/advanced-cache.php is generated, lives outside the plugin
 * directory, and was only ever written by activation — which does not fire on
 * a plugin update. Production consequently served a drop-in stamped
 * `Version: 0.2.0` against plugin 0.3.3 for roughly two and a half months.
 *
 * @package ExtraChillCache
 */

// phpcs:disable -- Standalone test harness intentionally stubs WordPress functions and writes CLI output directly.

define( 'ABSPATH', __DIR__ . '/' );
define( 'WP_CONTENT_DIR', __DIR__ . '/dropin-version-fixture' );
define( 'DAY_IN_SECONDS', 86400 );
define( 'MINUTE_IN_SECONDS', 60 );
define( 'EXTRACHILL_CACHE_PLUGIN_DIR', dirname( __DIR__ ) . '/' );
define( 'EXTRACHILL_CACHE_VERSION', '0.3.3' );

$GLOBALS['extrachill_cache_test_is_multisite'] = false;
$GLOBALS['extrachill_cache_test_transients']   = array();
$GLOBALS['extrachill_cache_test_wp_cache_set'] = 0;

function is_multisite() {
	return $GLOBALS['extrachill_cache_test_is_multisite'];
}

function get_sites( $args = array() ) {
	return array();
}

function wp_json_encode( $value, $flags = 0, $depth = 512 ) {
	return json_encode( $value, $flags, $depth );
}

function get_site_transient( $key ) {
	return isset( $GLOBALS['extrachill_cache_test_transients'][ $key ] )
		? $GLOBALS['extrachill_cache_test_transients'][ $key ]
		: false;
}

function set_site_transient( $key, $value, $ttl = 0 ) {
	$GLOBALS['extrachill_cache_test_transients'][ $key ] = $value;
	return true;
}

function apply_filters( $hook, $value ) {
	return $value;
}

function trailingslashit( $path ) {
	return rtrim( $path, '/\\' ) . '/';
}

require dirname( __DIR__ ) . '/inc/dropin-installer.php';

$failures = 0;

function dv_assert( $ok, $label ) {
	global $failures;
	echo ( $ok ? 'PASS' : 'FAIL' ) . ": {$label}\n";
	if ( ! $ok ) {
		++$failures;
	}
}

$fixture_dir = WP_CONTENT_DIR;
@mkdir( $fixture_dir, 0777, true );
$dropin = $fixture_dir . '/advanced-cache.php';

// ---------------------------------------------------------------------------
// The generated drop-in must declare the version it came from. Without this
// the plugin has nothing in memory to compare against and would have to read
// the file on every request to notice drift.
// ---------------------------------------------------------------------------
@unlink( $dropin );
$installed = extrachill_cache_install_dropin( false );
dv_assert( true === $installed, 'install writes the drop-in' );

$contents = (string) @file_get_contents( $dropin );
dv_assert(
	false !== strpos( $contents, "define( 'EXTRACHILL_CACHE_DROPIN_VERSION', '0.3.3' )" ),
	'generated drop-in declares the plugin version it was generated from'
);

// The exact drift seen in production: a drop-in generated by an older plugin.
$stale = str_replace(
	"define( 'EXTRACHILL_CACHE_DROPIN_VERSION', '0.3.3' )",
	"define( 'EXTRACHILL_CACHE_DROPIN_VERSION', '0.2.0' )",
	$contents
);
dv_assert( $stale !== $contents, 'fixture: a 0.2.0 drop-in differs from a 0.3.3 one' );

// ---------------------------------------------------------------------------
// Refresh must not rewrite wp-config.php. Activation owns WP_CACHE; an
// ordinary page load must not attempt a webroot write, which on a hardened
// install would fail anyway.
// ---------------------------------------------------------------------------
dv_assert(
	0 === $GLOBALS['extrachill_cache_test_wp_cache_set'],
	'refresh path does not touch the WP_CACHE constant'
);

// ---------------------------------------------------------------------------
// Staleness comparison. The real function reads a constant defined by the
// already-loaded drop-in, which cannot be redefined inside one test process,
// so the comparison itself is exercised directly.
// ---------------------------------------------------------------------------
$is_stale = static function ( $dropin_version ) {
	return $dropin_version !== EXTRACHILL_CACHE_VERSION;
};

dv_assert( $is_stale( '0.2.0' ), 'a 0.2.0 drop-in is detected as stale against 0.3.3' );
dv_assert( ! $is_stale( '0.3.3' ), 'a matching drop-in is not rewritten' );
dv_assert( $is_stale( '0.3.2' ), 'even a one-patch-old drop-in is stale' );

// ---------------------------------------------------------------------------
// A foreign drop-in must never be clobbered, refresh or not. This is the guard
// that keeps the version check from stomping another caching plugin.
// ---------------------------------------------------------------------------
file_put_contents( $dropin, "<?php\n// Breeze generated drop-in\n" );
dv_assert(
	false === extrachill_cache_install_dropin( false ),
	'a foreign drop-in is refused rather than overwritten'
);
dv_assert(
	false !== strpos( (string) file_get_contents( $dropin ), 'Breeze' ),
	'the foreign drop-in is left byte-intact'
);

// ---------------------------------------------------------------------------
// Backoff: a drop-in that cannot be written must not be retried on every
// request. The foreign drop-in above is exactly that case.
// ---------------------------------------------------------------------------
$GLOBALS['extrachill_cache_test_transients'] = array();
extrachill_cache_maybe_refresh_dropin();
dv_assert(
	false !== get_site_transient( 'extrachill_cache_dropin_refresh_backoff' ),
	'a failed refresh records a backoff instead of retrying every request'
);

@unlink( $dropin );
@rmdir( $fixture_dir );

if ( $failures > 0 ) {
	echo "{$failures} failure(s).\n";
	exit( 1 );
}
echo "All drop-in version checks passed.\n";
