<?php
/**
 * Drop-in installer.
 *
 * Writes / removes wp-content/advanced-cache.php (the early SERVE gate) and
 * ensures WP_CACHE is enabled so WordPress actually includes it.
 *
 * Modeled on how Breeze generated its own wp-content/advanced-cache.php with a
 * host->blog_id map baked in. Instead of code-generating a per-site switch, we
 * ship a static template (inc/dropin-template.php) and inject a small header of
 * constants above it: the cache dir, TTL, the shared store path, and a
 * host->blog_id JSON map built at install time from the live network.
 *
 * This module ONLY writes to production paths when the plugin is activated.
 * In the initial build PR the plugin is not activated, so nothing is written.
 *
 * @package ExtraChillCache
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Absolute path to the advanced-cache.php drop-in location.
 *
 * @return string
 */
function extrachill_cache_dropin_path() {
	return rtrim( WP_CONTENT_DIR, '/\\' ) . '/advanced-cache.php';
}

/**
 * Build the host => blog_id map for the current network.
 *
 * On single-site this returns an empty map (the drop-in then falls back to the
 * shared base cache dir). On multisite it enumerates sites and maps their host
 * to blog_id, mirroring the switch Breeze hand-maintained in its
 * advanced-cache.php.
 *
 * @return array<string,int>
 */
function extrachill_cache_build_blog_map() {
	$map = array();

	if ( is_multisite() && function_exists( 'get_sites' ) ) {
		$sites = get_sites( array( 'number' => 0 ) );
		foreach ( $sites as $site ) {
			$host = strtolower( (string) $site->domain );
			if ( '' !== $host ) {
				$map[ $host ] = (int) $site->blog_id;
			}
		}
	}

	return $map;
}

/**
 * Compose the full advanced-cache.php contents: injected constants + template.
 *
 * @return string|false Drop-in file contents, or false if template missing.
 */
function extrachill_cache_compose_dropin() {
	$template_path = EXTRACHILL_CACHE_PLUGIN_DIR . 'inc/dropin-template.php';
	// phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Reads a bundled local template file; runs at the drop-in install layer where WP_Filesystem is unavailable. The @ guards against a missing/unreadable file (handled via the false check below).
	$template = @file_get_contents( $template_path );
	if ( false === $template ) {
		return false;
	}

	// Strip the leading <?php from the template so we can prepend our own
	// header block cleanly.
	$template_body = preg_replace( '/^<\?php\s*/', '', $template, 1 );

	$store_path = EXTRACHILL_CACHE_PLUGIN_DIR . 'inc/cache-store.php';
	$cache_dir  = defined( 'EXTRACHILL_CACHE_DIR' )
		? EXTRACHILL_CACHE_DIR
		: rtrim( WP_CONTENT_DIR, '/\\' ) . '/cache/extrachill-cache';
	$ttl        = defined( 'EXTRACHILL_CACHE_TTL' ) ? (int) EXTRACHILL_CACHE_TTL : DAY_IN_SECONDS;

	$blog_map      = extrachill_cache_build_blog_map();
	$blog_map_json = wp_json_encode( $blog_map );

	$header  = "<?php\n";
	$header .= "/**\n";
	$header .= " * GENERATED by Extra Chill Cache — do not edit by hand.\n";
	$header .= ' * Regenerate via plugin (re)activation. Version: ' . EXTRACHILL_CACHE_VERSION . "\n";
	$header .= " */\n";
	$header .= "if ( ! defined( 'EXTRACHILL_CACHE_DIR' ) ) { define( 'EXTRACHILL_CACHE_DIR', " . var_export( $cache_dir, true ) . " ); }\n"; // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_var_export -- Code generation: exporting a scalar into the generated drop-in PHP, not debug logging.
	$header .= "if ( ! defined( 'EXTRACHILL_CACHE_TTL' ) ) { define( 'EXTRACHILL_CACHE_TTL', " . $ttl . " ); }\n";
	$header .= "if ( ! defined( 'EXTRACHILL_CACHE_STORE_PATH' ) ) { define( 'EXTRACHILL_CACHE_STORE_PATH', " . var_export( $store_path, true ) . " ); }\n"; // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_var_export -- Code generation: exporting a scalar into the generated drop-in PHP, not debug logging.
	$header .= "if ( ! defined( 'EXTRACHILL_CACHE_DROPIN_BLOG_MAP' ) ) { define( 'EXTRACHILL_CACHE_DROPIN_BLOG_MAP', " . var_export( $blog_map_json, true ) . " ); }\n"; // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_var_export -- Code generation: exporting a scalar into the generated drop-in PHP, not debug logging.
	$header .= "\n";

	return $header . $template_body;
}

/**
 * Install the advanced-cache.php drop-in and enable WP_CACHE.
 *
 * Refuses to overwrite a drop-in owned by another plugin (e.g. a leftover
 * Breeze advanced-cache.php) unless it is ours — the cutover docs instruct the
 * owner to remove Breeze's drop-in first.
 *
 * @return bool True on success.
 */
function extrachill_cache_install_dropin() {
	$dropin = extrachill_cache_dropin_path();

	// Guard: don't clobber a foreign drop-in. Ours contains this marker string.
	// phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged -- Defensive existence check at the drop-in install layer; a filesystem warning must not surface here.
	if ( @is_file( $dropin ) ) {
		// phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Reads the local advanced-cache.php drop-in; runs where WP_Filesystem is unavailable. The @ suppresses a benign read failure (cast to string handles it).
		$existing = (string) @file_get_contents( $dropin );
		if ( false === strpos( $existing, 'Extra Chill Cache' ) ) {
			// A non-ours drop-in (likely Breeze) is present. Do not overwrite.
			return false;
		}
	}

	$contents = extrachill_cache_compose_dropin();
	if ( false === $contents ) {
		return false;
	}

	// phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents -- Writes wp-content/advanced-cache.php directly; runs at the drop-in install layer before WP_Filesystem exists. The @ suppresses a benign write failure (handled via the false check).
	if ( false === @file_put_contents( $dropin, $contents, LOCK_EX ) ) {
		return false;
	}

	extrachill_cache_set_wp_cache_constant( true );

	return true;
}

/**
 * Remove our advanced-cache.php drop-in (only if it's ours).
 *
 * @return void
 */
function extrachill_cache_remove_dropin() {
	$dropin = extrachill_cache_dropin_path();
	// phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged -- Defensive existence check at the drop-in install layer; a filesystem warning must not surface here.
	if ( ! @is_file( $dropin ) ) {
		return;
	}

	// phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Reads the local drop-in to confirm ownership; runs where WP_Filesystem is unavailable. The @ suppresses a benign read failure (cast to string handles it).
	$existing = (string) @file_get_contents( $dropin );
	if ( false !== strpos( $existing, 'Extra Chill Cache' ) ) {
		// phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.WP.AlternativeFunctions.unlink_unlink -- Removes our own advanced-cache.php drop-in directly; runs at the drop-in layer before WP_Filesystem/wp_delete_file are guaranteed available.
		@unlink( $dropin );
	}
}

/**
 * Ensure the WP_CACHE constant is set to the requested value in wp-config.php.
 *
 * WordPress only includes advanced-cache.php when WP_CACHE is true. Breeze
 * managed this constant too. We only touch wp-config.php if the constant is
 * absent or set to the wrong value, and we never modify it if it's already
 * correct.
 *
 * @param bool $enabled Desired value.
 * @return bool True if the constant is (or was already) in the desired state.
 */
function extrachill_cache_set_wp_cache_constant( $enabled ) {
	if ( defined( 'WP_CACHE' ) && (bool) WP_CACHE === (bool) $enabled ) {
		return true;
	}

	$config_path = extrachill_cache_locate_wp_config();
	// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_is_writable -- Checks wp-config.php writability directly; runs at the drop-in install layer before WP_Filesystem exists.
	if ( '' === $config_path || ! is_writable( $config_path ) ) {
		return false;
	}

	// phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Reads wp-config.php directly to toggle WP_CACHE; runs where WP_Filesystem is unavailable. The @ suppresses a benign read failure (handled below).
	$config = (string) @file_get_contents( $config_path );
	if ( '' === $config ) {
		return false;
	}

	$value = $enabled ? 'true' : 'false';

	if ( preg_match( "/define\(\s*['\"]WP_CACHE['\"]\s*,/", $config ) ) {
		// Replace existing definition.
		$config = preg_replace(
			"/define\(\s*['\"]WP_CACHE['\"]\s*,\s*[^)]*\)\s*;/",
			"define( 'WP_CACHE', {$value} );",
			$config
		);
	} else {
		// Insert right after the opening PHP tag.
		$config = preg_replace(
			'/^<\?php\s*/',
			"<?php\ndefine( 'WP_CACHE', {$value} ); // Added by Extra Chill Cache.\n",
			$config,
			1
		);
	}

	// phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents -- Writes wp-config.php directly to toggle WP_CACHE; runs at the drop-in install layer before WP_Filesystem exists. The @ suppresses a benign write failure (returned as false).
	return false !== @file_put_contents( $config_path, $config, LOCK_EX );
}

/**
 * Locate wp-config.php (standard or one-level-up layout).
 *
 * @return string Path, or '' if not found/writable.
 */
function extrachill_cache_locate_wp_config() {
	$candidates = array(
		ABSPATH . 'wp-config.php',
		dirname( ABSPATH ) . '/wp-config.php',
	);

	foreach ( $candidates as $candidate ) {
		// phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged -- Defensive existence probe for wp-config.php at the drop-in install layer; a filesystem warning must not surface here.
		if ( @is_file( $candidate ) ) {
			return $candidate;
		}
	}

	return '';
}
